[package]
name = "rstennis"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.20.0"
minifb = "0.25"
url = "2.4.1"
serde_json = "1.0.107"
